# Numpy

In [1]:
import numpy as np

In [2]:
import array

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
# It will upcast the array in the biggest dtype here it will convert all elements into string
np.array([1,2,3,4,'sudh',2+0j])

array(['1', '2', '3', '4', 'sudh', '(2+0j)'], dtype='<U64')

In [6]:
# here it will upcast all the elements in the array into flaot
np.array([1,2,3,4.0,5.0])

array([1., 2., 3., 4., 5.])

In [7]:
#1D array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
#2D array
np.array([[1,3],[3,4],[6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [9]:
np.array([[1,3],[3,4],[6,7,8]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

# ndim

In [11]:
a=np.array([1,2,3,4,5])
a.ndim

1

In [12]:
np.array([1,2,3,4,5],ndmin=3)


array([[[1, 2, 3, 4, 5]]])

In [13]:
np.array([1,2,3,4,5],dtype=complex)


array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [14]:
# we can also write in list and tuple also it will consider it as array.
np.array([(1,2),(4,5)])

array([[1, 2],
       [4, 5]])

In [15]:
# We can change the dtype also by using this [(1,2),(4,5)] here a has <i2 dtype and b has <i8(<i2= 8+8, <i8=8+8+8+8+8+8+8+8)
arr=np.array([(1,2),(4,5)], dtype=[('a','<i2'),('b','<i8')])

In [16]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [17]:
type(arr[0][0])

numpy.int16

In [18]:
type(arr[0][1])

numpy.int64

In [19]:
type(arr[1][0])

numpy.int16

In [20]:
type(arr[1][1])

numpy.int64

In [21]:
arr2=np.array([(1,2),(4,5)])

In [22]:
#convert array into matrix
# mat and matrix both are same
mat=np.mat(arr2)
mat

matrix([[1, 2],
        [4, 5]])

In [23]:
# Array and matrix are 2 types of data type(Derived datatype of the primitive datatype)

In [24]:
np.matrix(arr2)

matrix([[1, 2],
        [4, 5]])

# To convert list into array we have 3 methods


In [25]:
l=[1,2,3,4,5]

### np.array()

In [26]:
np.array(l)

array([1, 2, 3, 4, 5])

### np.asarray()

In [27]:
np.asarray(l)

array([1, 2, 3, 4, 5])


### np.asanyarray()

In [28]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

# Difference between asarray and asanyarray


In [29]:
# asarray -> It will convert directly into the array it will not check the form of array.
np.asarray(mat)

array([[1, 2],
       [4, 5]])

In [30]:
# asanyarray -> It first check is the data is in the form of array then it will not convert it inot array and
# if the data is not in the form of array then only it will convert data into array.
np.asanyarray(mat)

matrix([[1, 2],
        [4, 5]])

# Matrix is the subset of the array

In [31]:
issubclass(np.ndarray,np.matrix)

False

In [32]:

issubclass(np.matrix,np.ndarray)

True

# Shallow copy and deep copy

In [33]:
arr3=np.array([[1,2],[3,4]])

In [34]:
arr3

array([[1, 2],
       [3, 4]])

In [35]:
# Shallow copy
a=arr3

In [36]:
a

array([[1, 2],
       [3, 4]])

In [37]:
#Deep copy
b=np.copy(arr3)

In [38]:
b

array([[1, 2],
       [3, 4]])

In [39]:
arr3[0][0]

1

In [40]:
arr3[0][0]=64

In [41]:
arr3

array([[64,  2],
       [ 3,  4]])

In [42]:
a

array([[64,  2],
       [ 3,  4]])

In [43]:
b

array([[1, 2],
       [3, 4]])

## Difference Between deep copy and shallow copy

##### 1)Shallow copy  will affect if we change in the original array
##### 2)Deep copy will not affected if we are doing changes in original array

# Difference between numpy array and list
1)Numpy array is the function of numpy package and all numeric functions of numpy is directly applicable to numpy array directly.

2)list is the part of core python

#  ** fromfunction()

In [44]:
np.fromfunction(lambda i,j:i==j,(4,4))
# Explaination
#(4,4) -> i= row values,j=column values
#   0 1 2 3
# 0  T F F F
# 1  F T F F
# 2  F F T F
# 3  F F F T

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [45]:
np.fromfunction(lambda i,j:i*j,(4,4))


array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [46]:
np.fromfunction(lambda i,j:i/j,(3,3))


C:\Users\HP\AppData\Local\Temp\ipykernel_9376\1972042526.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i,j:i/j,(3,3))
C:\Users\HP\AppData\Local\Temp\ipykernel_9376\1972042526.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i,j:i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

# Convert Generator into array

#### np.fromiter function is used to convert generator into array

In [47]:
gen=(i*i for i in range(5))

In [48]:
gen

<generator object <genexpr> at 0x000001E41894D630>

In [49]:
def test(x):
    yield x

In [50]:
test(5)

<generator object test at 0x000001E418A07F40>

In [51]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [52]:
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

# Convert string into array

In [53]:
np.fromstring('1,2,3,4,5',sep=',',dtype=int)

array([1, 2, 3, 4, 5])

In [54]:
np.fromstring('111 222 333 444',sep=' ',dtype=float)

array([111., 222., 333., 444.])

In [55]:
np.fromstring('11#22#33#44',sep='#',dtype=complex)

array([11.+0.j, 22.+0.j, 33.+0.j, 44.+0.j])

# size and shape

In [57]:
a=np.array([[1,2,3],[4,5,6]])

In [58]:
a.ndim

2

In [59]:
a.size

6

In [60]:
a.shape

(2, 3)

In [61]:
a2=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [62]:
a2.ndim

3

In [63]:
a2.shape (2 array with 2 rows and 3 columns)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (19210881.py, line 1)

In [64]:
a2.size

12

# 3D array

In [65]:
a3=np.array([[[[1,2,3],[4,5,6]],[[5,6,7],[8,9,6]],[[3,7,1],[5,9,2]]]])

In [66]:
a3.ndim

4

In [67]:
a3.shape

(1, 3, 2, 3)

# arange and range function

### np.arange -> it accept float value also
### range -> it will not accept float value

In [68]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [69]:
list(range(6.6))

TypeError: 'float' object cannot be interpreted as an integer

In [70]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [71]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [72]:
 np.arange(6.6,9,.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [73]:
list(range(6.6,9,.3))

TypeError: 'float' object cannot be interpreted as an integer

In [74]:
np.arange(9,6.6,-0.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [75]:
list(range(9,6,-3))

[9]

# linspace function

In [76]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [77]:
np.linspace(8,10)

array([ 8.        ,  8.04081633,  8.08163265,  8.12244898,  8.16326531,
        8.20408163,  8.24489796,  8.28571429,  8.32653061,  8.36734694,
        8.40816327,  8.44897959,  8.48979592,  8.53061224,  8.57142857,
        8.6122449 ,  8.65306122,  8.69387755,  8.73469388,  8.7755102 ,
        8.81632653,  8.85714286,  8.89795918,  8.93877551,  8.97959184,
        9.02040816,  9.06122449,  9.10204082,  9.14285714,  9.18367347,
        9.2244898 ,  9.26530612,  9.30612245,  9.34693878,  9.3877551 ,
        9.42857143,  9.46938776,  9.51020408,  9.55102041,  9.59183673,
        9.63265306,  9.67346939,  9.71428571,  9.75510204,  9.79591837,
        9.83673469,  9.87755102,  9.91836735,  9.95918367, 10.        ])

In [78]:
np.linspace(1,2,5)
# here it will generate 5 numbers between 1 to 2 linspace is used to generate the numbers in equal distance.

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [80]:
# by default it will give 50 num of data
np.linspace(2,8)

array([2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
       2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
       3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
       3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
       4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551,
       5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
       5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
       6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
       6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
       7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ])

In [81]:
# here we mention 1 to 6 bcz we want data from 1 to 6 and we want 10 data by default it is 50
np.linspace(1,6,10)

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

In [82]:
# it will not include endpoint (axis=0(row))
np.linspace(1,6,10,endpoint=False)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [83]:
np.linspace(1,6,10,endpoint=False,axis=0)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [84]:
np.linspace(1,6,10,endpoint=False,axis=1)

AxisError: destination: axis 1 is out of bounds for array of dimension 1

In [86]:
np.linspace([1,6],10,endpoint=False,axis=1)
# here in this it will create 2 arrays in first array it will start from 1 to before 10 and second array it will start from 7 to end before 10

array([[1.  , 1.18, 1.36, 1.54, 1.72, 1.9 , 2.08, 2.26, 2.44, 2.62, 2.8 ,
        2.98, 3.16, 3.34, 3.52, 3.7 , 3.88, 4.06, 4.24, 4.42, 4.6 , 4.78,
        4.96, 5.14, 5.32, 5.5 , 5.68, 5.86, 6.04, 6.22, 6.4 , 6.58, 6.76,
        6.94, 7.12, 7.3 , 7.48, 7.66, 7.84, 8.02, 8.2 , 8.38, 8.56, 8.74,
        8.92, 9.1 , 9.28, 9.46, 9.64, 9.82],
       [6.  , 6.08, 6.16, 6.24, 6.32, 6.4 , 6.48, 6.56, 6.64, 6.72, 6.8 ,
        6.88, 6.96, 7.04, 7.12, 7.2 , 7.28, 7.36, 7.44, 7.52, 7.6 , 7.68,
        7.76, 7.84, 7.92, 8.  , 8.08, 8.16, 8.24, 8.32, 8.4 , 8.48, 8.56,
        8.64, 8.72, 8.8 , 8.88, 8.96, 9.04, 9.12, 9.2 , 9.28, 9.36, 9.44,
        9.52, 9.6 , 9.68, 9.76, 9.84, 9.92]])

### np.arange(),np.linspace() these are the functions used for generatingthe data

# zeros() function

### 1D array

In [87]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### 2D array

In [90]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### 3D array

In [92]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### 4D array

In [94]:
np.zeros((2,4,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

# Ones Function

### 1D array

In [97]:
np.ones(5)

array([1., 1., 1., 1., 1.])

### 2D array

In [99]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### 3D array

In [103]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### 4D array

In [105]:
np.ones((2,2,3,4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [106]:
np.ones((2,2,3,4))+5

array([[[[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]],

        [[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]],


       [[[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]],

        [[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]]])

# empty function

### Defination = Return a new array of a given shape and type, with random values.

In [107]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [108]:
np.empty(6)

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304, 7.74860419e-304,
       7.74860419e-304, 7.74860419e-304])

In [109]:
np.empty((2,3))

array([[7.74860419e-304, 7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304, 7.74860419e-304]])

In [110]:
np.empty((2,3,1))

array([[[7.74860419e-304],
        [7.74860419e-304],
        [7.74860419e-304]],

       [[7.74860419e-304],
        [7.74860419e-304],
        [7.74860419e-304]]])

In [111]:
np.empty((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [112]:
np.empty((2,2,3,1))

array([[[[1.01855798e-312],
         [1.10343781e-312],
         [1.01855798e-312]],

        [[9.54898106e-313],
         [1.03977794e-312],
         [1.01855798e-312]]],


       [[[1.23075756e-312],
         [1.03977794e-312],
         [1.01855798e-312]],

        [[9.76118064e-313],
         [1.14587773e-312],
         [1.90979621e-312]]]])

# eye function

In [114]:
# it is used to create identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [115]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# logspace function

### logspace() function is similar to linspace but logspace giving us the log value with the base ... by default base is 10
### in logspace bydefault the base is 10 it will calculate log of 2,2.2,3,.... with respect to base e.g for log 2 it will calculate log 2 to the base 10


In [116]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [117]:
np.logspace(2,3,5,axis=1)

AxisError: destination: axis 1 is out of bounds for array of dimension 1

In [118]:
np.logspace([2],[3],5,axis=1)

array([[ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
        1000.        ]])

In [119]:
np.logspace([2],[3],5,axis=0)

array([[ 100.        ],
       [ 177.827941  ],
       [ 316.22776602],
       [ 562.34132519],
       [1000.        ]])

In [120]:
np.logspace(2,3,4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [121]:
np.logspace(2,3,4,base=5)

array([ 25.        ,  42.74939867,  73.10044346, 125.        ])

In [123]:
np.logspace(2,3,4,base=10) # axis 0 is row

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

# We can use this function in daily basis

In [127]:
d=np.linspace(4,7,40)

In [128]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [129]:
d.ndim

1

In [130]:
d.shape

(40,)

In [131]:
d.size

40

In [132]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [133]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [135]:
d.reshape(1,2,1,20)

array([[[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
          4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
          4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
          5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

        [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
          5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
          6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
          6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]]])

In [136]:
np.arange(2,10,2)

array([2, 4, 6, 8])

# Array is collection of homogeneous type of data and nd array is the collection of hoterogeneous type of data

In [138]:
import array as arr

In [140]:
arr.array('i',[1,2,3])

array('i', [1, 2, 3])

In [141]:
np.array([1,2,'abc'])

array(['1', '2', 'abc'], dtype='<U11')

# random module

In [142]:
np.random.rand(3)

array([0.61391751, 0.7989876 , 0.05462146])

In [143]:
np.random.randn(3)

array([ 0.24833848,  0.9534253 , -1.01694005])

# Difference between randn and rand function

### 1)Differ in the type of distribution they use
### 2)rand-> 
###        * Distribution: Uniform distribution
###        * Range:[ 0,1)
###        *Usage: Generates random samples from a uniform distribution over 0,1 (0 include 1 is not included)
### 3)randn->
###         * Distribution:Standard normal distribution (Gaussian distribution).
###         * Mean: 0
###         *Standard Deviation: 1
###         *Usage: Generates random samples from a standard normal distribution.
### 4)Distribution:
### rand: Uniform distribution
### randn: Standard normal distribution.
### 5)Range:
### rand:[0,1)
### randn: (-infinity, infinity) ( with a higher concentration around 0,following the bell curve of the normal distribution.
### 6)Typical use cases:
### rand: Useful when you need random numbers in a specific range (e.g.  for initializing weights in a neural network, simulating probabilities,etc.)
### randn: Useful when you need data that follows a normal distribution (e.g. for statistical simulations,generating noise, etc.)


In [147]:
two=np.random.randn(3,4)

In [148]:
two

array([[ 1.09380503,  1.08442426,  0.43823939,  1.23678101],
       [-0.82446007,  0.53827832,  0.6735943 ,  0.0627167 ],
       [ 0.56578452,  1.45346204,  0.17056974,  0.7549693 ]])

In [149]:
two.ndim

2

In [150]:
three=np.random.rand(2,3,4)

In [151]:
three

array([[[0.36009495, 0.74148194, 0.79511956, 0.18318507],
        [0.70677392, 0.39296144, 0.56978562, 0.1520377 ],
        [0.1614796 , 0.84376544, 0.32753185, 0.86981987]],

       [[0.02713128, 0.97298071, 0.03759361, 0.81715298],
        [0.92276874, 0.07298208, 0.01401142, 0.68948674],
        [0.95334397, 0.04840188, 0.14566077, 0.18093325]]])

In [152]:
three.ndim

3

In [153]:
four=np.random.randn(2,2,3,4)

In [154]:
four

array([[[[-1.16462355,  0.84841137, -0.50981738,  0.71841018],
         [-0.13997657,  0.75679214,  0.69455186, -0.35312043],
         [-0.15216137, -0.36734649, -1.65898403, -1.19831253]],

        [[-0.16967711,  0.55720902,  1.49865348,  0.33215858],
         [-0.39442956,  0.62779613,  0.13129645, -1.89816354],
         [-0.19161377, -1.23955861, -0.49584021, -0.97198545]]],


       [[[-0.34857093, -0.15361588, -0.70150406, -0.25400593],
         [-1.56118676, -0.02968636,  0.3617145 ,  1.42055871],
         [ 0.45002075, -0.40623553, -1.80168115,  0.2356182 ]],

        [[ 0.93894203, -0.26076758, -0.3976362 ,  0.81863326],
         [ 1.61350148,  0.96590005,  0.06661616,  0.25289943],
         [-0.18270867,  1.70262484,  0.80770276,  0.52273964]]]])

In [155]:
four.ndim

4

In [158]:
# it will generate the data between 0 to 5
np.random.randint(5)

0

In [159]:
# it will generate the data between 5 to 20
np.random.randint(5,20)

8

In [161]:
#it will generate four * four matrix between the range 5 to 50
np.random.randint(5,50,(4,4))

array([[26, 15, 30,  7],
       [48, 44, 30, 15],
       [ 7, 25, 12, 15],
       [22, 46, 38, 19]])

In [164]:
arr=np.random.randint(3,9,(3,3))

In [165]:
arr

array([[7, 3, 3],
       [8, 6, 6],
       [4, 7, 8]])

In [166]:
arr.reshape(9,1)

array([[7],
       [3],
       [3],
       [8],
       [6],
       [6],
       [4],
       [7],
       [8]])

In [167]:
arr.reshape(1,3,3)

array([[[7, 3, 3],
        [8, 6, 6],
        [4, 7, 8]]])

In [169]:
arr.reshape(1,1,9)

array([[[7, 3, 3, 8, 6, 6, 4, 7, 8]]])

In [170]:
arr.reshape(1,3,3)

array([[[7, 3, 3],
        [8, 6, 6],
        [4, 7, 8]]])

In [172]:
arr.reshape(3,3,1,1)

array([[[[7]],

        [[3]],

        [[3]]],


       [[[8]],

        [[6]],

        [[6]]],


       [[[4]],

        [[7]],

        [[8]]]])

In [173]:
# here the shape of arr is 9 so if i pass negative number at the end at starting we give one number so second or end number it will automatically take
# e.g
arr.reshape(3,-1)

array([[7, 3, 3],
       [8, 6, 6],
       [4, 7, 8]])

In [176]:
arr.reshape(4,-1) # here it is giving error bcz 4 multiply anthing is never 9 bcz the size of arr is 9 thats why we want 9 size

ValueError: cannot reshape array of size 9 into shape (4,newaxis)

In [177]:
arr.reshape(1,-1) # it will automatically take 9 as a second number

array([[7, 3, 3, 8, 6, 6, 4, 7, 8]])

In [178]:
arr.reshape(1,-1454545) # it will automatically take 9 as a second number

array([[7, 3, 3, 8, 6, 6, 4, 7, 8]])

In [179]:
arr

array([[7, 3, 3],
       [8, 6, 6],
       [4, 7, 8]])

In [181]:
arr.max()

8

In [182]:
arr.min()

3

In [186]:
arr=np.random.randint(4,10,(5,5))

In [187]:
arr

array([[8, 5, 7, 7, 5],
       [8, 5, 7, 4, 9],
       [4, 7, 9, 5, 8],
       [4, 4, 6, 7, 6],
       [8, 5, 6, 9, 4]])

In [190]:
# slicing first we give the index of row and then column
arr[3:,3:]

array([[7, 6],
       [9, 4]])

In [194]:
arr[:,1::2]

array([[5, 7],
       [5, 4],
       [7, 5],
       [4, 7],
       [5, 9]])

In [195]:
arr[:,[1,3]]

array([[5, 7],
       [5, 4],
       [7, 5],
       [4, 7],
       [5, 9]])

### Note = We can use reshape at the time of image resize , audio resize, video resize, etc.

In [199]:
arr>5

array([[ True, False,  True,  True, False],
       [ True, False,  True, False,  True],
       [False,  True,  True, False,  True],
       [False, False,  True,  True,  True],
       [ True, False,  True,  True, False]])

In [201]:
arr[arr>5] # it is filter the condition it is giving array whose value is greater than 5

array([8, 7, 7, 8, 7, 9, 7, 9, 8, 6, 7, 6, 8, 6, 9])

In [202]:
arr * arr

array([[64, 25, 49, 49, 25],
       [64, 25, 49, 16, 81],
       [16, 49, 81, 25, 64],
       [16, 16, 36, 49, 36],
       [64, 25, 36, 81, 16]])

In [203]:
arr1=np.random.randint(2,3,(3,3))

In [204]:
arr2=np.random.randint(2,5,(3,3))

In [205]:
arr1

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [206]:
arr2

array([[2, 4, 4],
       [2, 4, 2],
       [2, 4, 3]])

In [208]:
arr1*arr2

array([[4, 8, 8],
       [4, 8, 4],
       [4, 8, 6]])

In [210]:
arr1@arr2 # matrix multiplication

array([[12, 24, 18],
       [12, 24, 18],
       [12, 24, 18]])

In [211]:
arr/0

C:\Users\HP\AppData\Local\Temp\ipykernel_9376\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [213]:
arr**2  # it will calculate  square of each element

array([[64, 25, 49, 49, 25],
       [64, 25, 49, 16, 81],
       [16, 49, 81, 25, 64],
       [16, 16, 36, 49, 36],
       [64, 25, 36, 81, 16]])

# Broadcasting

In [214]:
arr=np.zeros((3,4))

In [215]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [216]:
a=np.array([1,2,3,4])

In [223]:
arr+a
# here this a will braodcast to the each row of arr
# this is row wise broadcasting

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [221]:
arr+5
# here 5 will braodcast for each element of arr

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [224]:
a=np.array([1,2,3])

In [226]:
arr+a
# it will not braodcasting bcz of shape

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [227]:
# if we want braodcasting column wise
a=np.array([1,2,3])

In [231]:
# now if we want braodcasting (arr+a) column wise then we need 3*1
b=a.reshape(3,1)

In [232]:
arr+b

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [234]:
# we can also do the same thing using transpose
a=np.array([[1,2,3]])

In [235]:
a.T

array([[1],
       [2],
       [3]])

In [236]:
a.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [241]:
arr=np.random.rand(5,4)

In [242]:
arr

array([[0.39998935, 0.02221069, 0.60259921, 0.13135993],
       [0.35445994, 0.22701458, 0.34697129, 0.38936317],
       [0.32670733, 0.4883491 , 0.93779474, 0.24849079],
       [0.07864374, 0.33154438, 0.06002291, 0.19813321],
       [0.56287518, 0.56853437, 0.16265543, 0.81134213]])

In [243]:
np.sqrt(arr)

array([[0.63244712, 0.14903253, 0.77627264, 0.36243611],
       [0.59536538, 0.47646047, 0.58904269, 0.62398972],
       [0.57158318, 0.69881979, 0.96839803, 0.49848851],
       [0.28043491, 0.5757989 , 0.24499574, 0.44512156],
       [0.75025008, 0.75401218, 0.40330563, 0.90074532]])

In [244]:
np.exp(arr)

array([[1.49180882, 1.02245919, 1.82686103, 1.14037817],
       [1.42541064, 1.25484816, 1.41477611, 1.47604051],
       [1.38639566, 1.62962365, 2.55434221, 1.28208901],
       [1.08181885, 1.39311797, 1.06186088, 1.21912478],
       [1.75571324, 1.76567732, 1.17663119, 2.25092699]])

In [245]:
np.log10(arr)

array([[-0.39795157, -1.65343787, -0.21997144, -0.88153708],
       [-0.45043284, -0.64394626, -0.45970646, -0.40964513],
       [-0.48584113, -0.31126961, -0.02789221, -0.6046897 ],
       [-1.10433584, -0.47945833, -1.22168293, -0.70304273],
       [-0.2495879 , -0.24524328, -0.78873143, -0.09079597]])

In [246]:
arr1=np.random.randint(3,6,(3,4))

In [247]:
arr1

array([[4, 5, 4, 4],
       [4, 5, 4, 4],
       [3, 3, 3, 5]])

In [248]:
np.log10(arr1)

array([[0.60205999, 0.69897   , 0.60205999, 0.60205999],
       [0.60205999, 0.69897   , 0.60205999, 0.60205999],
       [0.47712125, 0.47712125, 0.47712125, 0.69897   ]])

In [249]:
# we will change the base also
np.log2(arr1)

array([[2.        , 2.32192809, 2.        , 2.        ],
       [2.        , 2.32192809, 2.        , 2.        ],
       [1.5849625 , 1.5849625 , 1.5849625 , 2.32192809]])